name: Run Unit Tests
run-name: Run Unit Tests
on: [push]
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - uses: actions/checkout@v3
          
      - name: Build Project
        run: dotnet build MiraBot

      - name: Run Unit Tests
        run: dotnet test